# Generated by Django 5.2.4 on 2025-07-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlserver', '0003_remove_massestimationtask_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massestimationtask',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
    ]
