version: '3.8'

services:
  # 🎨 Frontend (개발 모드)
  frontend:
    build:
      context: ./project1/frontend
      dockerfile: Dockerfile.dev
    container_name: food-calorie-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ML_API_URL=http://localhost:8001
    volumes:
      - ./project1/frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - backend
      - ml-server
    networks:
      - food-calorie-network

  # 🔧 Backend (개발 모드)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-calorie-backend-dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ML_SERVER_URL=http://ml-server:8001
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    command: uv run manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
      - celery
    networks:
      - food-calorie-network

  # 🤖 ML Server (개발 모드)
  ml-server:
    build:
      context: ./MLServer
      dockerfile: Dockerfile
    container_name: food-calorie-ml-server-dev
    ports:
      - "8001:8001"
    environment:
      - DEBUG_MODE=true
      - ENABLE_MULTIMODAL=true
      - LLM_PROVIDER=gemini
      - LLM_MODEL_NAME=gemini-2.5-flash
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - ./MLServer/.env
    volumes:
      - ./MLServer:/app
      - ./MLServer/logs:/app/logs
      - ./MLServer/results:/app/results
      - ./MLServer/data:/app/data
      - ./MLServer/weights:/app/weights
    command: python -m uvicorn api.main:app --reload --host 0.0.0.0 --port 8001
    networks:
      - food-calorie-network

  # 📊 Redis
  redis:
    image: redis:7-alpine
    container_name: food-calorie-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    networks:
      - food-calorie-network

  # ⚡ Celery Worker
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-calorie-celery-dev
    command: uv run celery -A config worker -l info --pool=solo
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ML_SERVER_URL=http://ml-server:8001
    networks:
      - food-calorie-network

volumes:
  redis_data_dev:

networks:
  food-calorie-network:
    driver: bridge