# Generated by Django 5.2.4 on 2025-07-24 13:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallenge",
            name="challenge_cutoff_time",
            field=models.TimeField(
                default=datetime.time(23, 0), help_text="챌린지 인정 마감 시간 (이후 식사는 무효)"
            ),
        ),
        migrations.AddField(
            model_name="userchallenge",
            name="min_daily_meals",
            field=models.IntegerField(
                choices=[(1, "1회"), (2, "2회"), (3, "3회"), (4, "4회"), (5, "5회")],
                default=2,
                help_text="하루 최소 식사 횟수",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
