# Generated by Django 5.2.4 on 2025-07-27 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_userchallenge_challenge_cutoff_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userchallenge",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="userchallenge",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dailychallengerecord",
            name="is_cheat_day",
            field=models.BooleanField(default=False, help_text="치팅 사용 여부"),
        ),
        migrations.AlterField(
            model_name="dailychallengerecord",
            name="is_success",
            field=models.BooleanField(default=False, help_text="성공 여부"),
        ),
        migrations.AlterField(
            model_name="dailychallengerecord",
            name="meal_count",
            field=models.IntegerField(default=0, help_text="해당 날짜 식사 횟수"),
        ),
        migrations.AlterField(
            model_name="dailychallengerecord",
            name="target_calories",
            field=models.FloatField(default=0, help_text="목표 칼로리"),
        ),
        migrations.AlterField(
            model_name="dailychallengerecord",
            name="total_calories",
            field=models.FloatField(default=0, help_text="해당 날짜 총 칼로리"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "진행중"),
                    ("inactive", "비활성"),
                    ("completed", "완료"),
                    ("quit", "포기"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userchallenge",
            unique_together={("user", "room", "status")},
        ),
        migrations.AddIndex(
            model_name="dailychallengerecord",
            index=models.Index(
                fields=["user_challenge", "date"], name="daily_chall_user_ch_355fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailychallengerecord",
            index=models.Index(fields=["date"], name="daily_chall_date_877b6a_idx"),
        ),
        migrations.AddIndex(
            model_name="dailychallengerecord",
            index=models.Index(
                fields=["is_success"], name="daily_chall_is_succ_80b089_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailychallengerecord",
            index=models.Index(
                fields=["is_cheat_day"], name="daily_chall_is_chea_c7c693_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchallenge",
            index=models.Index(
                fields=["user", "status"], name="user_challe_user_id_af83b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchallenge",
            index=models.Index(
                fields=["room", "status"], name="user_challe_room_id_7408dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchallenge",
            index=models.Index(
                fields=["current_streak_days"], name="user_challe_current_d85b07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchallenge",
            index=models.Index(
                fields=["challenge_start_date"], name="user_challe_challen_f4a482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchallenge",
            index=models.Index(
                fields=["status", "remaining_duration_days"],
                name="user_challe_status_54954a_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="dailychallengerecord",
            table="daily_challenge_record",
        ),
        migrations.AlterModelTable(
            name="userchallenge",
            table="user_challenge",
        ),
    ]
