# Generated by Django 5.2 on 2025-07-31 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_alter_userchallenge_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userchallenge",
            unique_together=set(),
        ),
    ]
