# Generated by Django 5.2.4 on 2025-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integrated', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
