# Generated by Django 5.2.4 on 2025-07-25 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_integrated", "0002_challenge_badge_challengeparticipant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengeparticipant",
            name="challenge",
        ),
        migrations.AlterUniqueTogether(
            name="challengeparticipant",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="challengeparticipant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="challengeprogress",
            name="participant",
        ),
        migrations.AlterUniqueTogether(
            name="challengeprogress",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="ChallengeParticipant",
        ),
        migrations.DeleteModel(
            name="ChallengeProgress",
        ),
    ]
