# Generated by Django 5.2.4 on 2025-07-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integrated', '0002_alter_meallog_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='nutriScore',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('UNKNOWN', 'UNKNOWN')], max_length=10, null=True),
        ),
    ]
